### ISSUE TITLE
document.querySelectorAll('p'); and $("p");

### ISSUE THREAD

**Issue by igoreskin** [learn-co-curriculum/js-dom-and-events-selecting-single-elements-readme#1]
document.querySelectorAll('p'); and $("p"); don't seem to be the same thing - $("p"); only returns the first matching element, like document.querySelector('p'); .

**Comment by maxwellbenton** [comment]
Hi there @igoreskin,

I'm having difficulty reproducing the issue, so I'm going to close it for now. You are correct that document.querySelectorAll('p') and $('p') do not return exactly the same thing, querySelectorAll returns a NodeList, while $('p') returns a jQuery collection, but both return a collection of all 'p' tags on a page.  

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
