### ISSUE TITLE
Website Bug

### ISSUE THREAD

**Issue by Ahmed-Sarkawt** [learn-co-curriculum/js-dom-and-events-selecting-single-elements-readme#3]
If you use console the IDE appears for a second. And this happens while expanding the height of the developer tools.
you can see it in this screenshots that I took:
https://i.imgur.com/BJ7oij7.png
https://i.imgur.com/hO76SOf.png

**Comment by drakeltheryuujin** [comment]
Hi there! 
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
